### ISSUE TITLE
make build crashes

### ISSUE THREAD

**Issue by leentorenvliet** [hectcastro/docker-riak#42]
Somewhere in building it tries to
/usr/bin/chfn -f Riak user riak
which is of course impossible. I'm guessing someone forget to escape the space,
or forgot an underscore as in Riak_user.
After that, the dpkg also crashes, but that might be related.
How can I fix this?

**Comment by hectcastro** [comment]
Are you working with the most recent release?

**Comment by leentorenvliet** [comment]
Yes. I cloned it from the github, then did make build

**Comment by hectcastro** [comment]
Can you please post the error message? I have been unable to reproduce a container build error locally.

**Comment by leentorenvliet** [comment]
Certainly:

docker build -t "hectcastro/riak" .
Sending build context to Docker daemon 173.1 kB

Sending build context to Docker daemon 
Step 0 : FROM phusion/baseimage:0.9.14
 ---> e74fe19c755c
Step 1 : MAINTAINER Hector Castro hectcastro@gmail.com
 ---> Using cache
 ---> 5f9b498881b3
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 0670d8ff85ad
Step 3 : ENV RIAK_VERSION 2.0.2-1
 ---> Using cache
 ---> a66bf86d0eca
Step 4 : RUN sed -i.bak 's/main$/main universe/' /etc/apt/sources.list
 ---> Using cache
 ---> 73b8a1f59b6d
Step 5 : RUN apt-get update -qq && apt-get install -y software-properties-common &&    apt-add-repository ppa:webupd8team/java -y && apt-get update -qq &&    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&    apt-get install -y oracle-java7-installer
 ---> Using cache
 ---> f995da8556ae
Step 6 : RUN curl https://packagecloud.io/install/repositories/basho/riak/script.deb.sh | bash
 ---> Using cache
 ---> 1ad3096ff22c
Step 7 : RUN apt-get install -y riak=${RIAK_VERSION}
 ---> Running in 13a26b05c65e
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  riak
0 upgraded, 1 newly installed, 0 to remove and 94 not upgraded.
Need to get 55.0 MB of archives.
After this operation, 78.9 MB of additional disk space will be used.
Fetched 55.0 MB in 19s (2826 kB/s)
Selecting previously unselected package riak.
(Reading database ... 16574 files and directories currently installed.)
Preparing to unpack .../riak_2.0.2-1_amd64.deb ...
Unpacking riak (2.0.2-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up riak (2.0.2-1) ...
Adding group `riak' (GID 106) ...
Done.
Adding system user `riak' (UID 103) ...
Adding new user `riak' (UID 103) with group `riak' ...
[91mchfn: PAM: System error
[0m[91madduser: `/usr/bin/chfn -f Riak user riak' returned error code 1. Exiting.
[0m[91mdpkg: error processing package riak (--configure):
 subprocess installed post-installation script returned error exit status 1
[0mProcessing triggers for ureadahead (0.100.0-16) ...
[91mErrors were encountered while processing:
[0m[91m riak
[0m[91mE[0m[91m: Sub-process /usr/bin/dpkg returned an error code (1)
[0m2015/08/16 19:11:53 The command [/bin/sh -c apt-get install -y riak=${RIAK_VERSION}] returned a non-zero code: 100
make: *** [build] Error 1

**Comment by hectcastro** [comment]
This looks a lot like https://github.com/docker/docker/issues/6345. Can you determine if you're running:

- A recent version of Docker
- The affected kernel version

**Comment by leentorenvliet** [comment]
I have recently installed docker, as the computer needed a new system. 
docker --version says
version 1.0.1 build 990021a
Could that be the problem?

**Comment by leentorenvliet** [comment]
Actually, that's right on the nose.

docker run -i -t ubuntu adduser --system --quiet --home /var/lib/postgresql --no-create-home \
            --shell /bin/bash --group --gecos "PostgreSQL administrator" postgres

produced the same (predicted) result. Thanks. Would no doubt have taken me days to figure out. It's a bit of a worry, since I do need need riak and I don't want to keep the big databases around after the work is done. There are some workarounds, but since no one is able to build a docker container while this bug is around, I expect it to be fixed soon. Thanks for your help (again).

**Comment by hectcastro** [comment]
Docker is currently at v1.8.1, so it is most likely already fixed. I'd try installing Docker from their [official package repositories](http://blog.docker.com/2015/07/new-apt-and-yum-repos/). That should get you on a more recent version.

**Comment by leentorenvliet** [comment]
It works! Great! and sorry for the confusion.

**Comment by hectcastro** [comment]
No problem. Glad it worked out!
